model:
    arch: fcn8s
data:
    dataset: HH_VV_VH_HV
    train_split: train_aug
    val_split: val
    img_rows: 'same'
    img_cols: 'same'
    path: VOC2012
    sbd_path: /private/home/meetshah/datasets/VOC/benchmark_RELEASE/
training:
    train_iters: 15000
    batch_size: 32
    val_interval: 100
    n_workers: 4
    print_interval: 5
    optimizer:
        name: 'sgd'
        lr: 1.0e-11
        weight_decay: 0.0005
        momentum: 0.99
    loss:
        name: 'cross_entropy'
        size_average: False
    lr_schedule:
    resume: runs/fcn8s_pascal/ /fcn8s_HH_VV_VH_HV_best_model.pkl
